# Visit http://dev.bukkit.org/server-mods/itemstowarp/ for more info.
currency:
  amount: 20
  item: 331

sign:
  protected: true

DB:
  driver: 'org.sqlite.JDBC'
  url: 'jdbc:sqlite:{DIR}{NAME}.db'
  username: 'root'
  password: ''
  isolation: 'SERIALIZABLE'
  logging: false
  rebuild: false