name: ItemstoWarp
version: 1.2.0
description: A pay to warp system
authors: [Muddr]
main: com.gtdclan.itemstowarp.Main
database: true

commands:
  itw:
    description: Main command for ItemstoWarp.
    usage: Error! Type /<command> for help.

    
permissions:
  itemstowarp.create:
    description: Creates a warp.
    default: true
  itemstowarp.makeprivate:
    description: Toggle their warp public/private.
    default: true
  itemstowarp.makeprivate.any:
    description: Toggle any warp public/private.
    default: op
  itemstowarp.remove:
    description: Removes your warp.
    default: true
  itemstowarp.remove.any:
    description: Removes any warp.
    default: op
  itemstowarp.warp:
    description: Warps player to non-private warps.
    default: true
  itemstowarp.warp.any:
    description: Warps player to any warps, should also have itemstowarp.list.all
    default: op
  itemstowarp.warp.nocost:
    description: Bypasses warp fee.
    default: false
  itemstowarp.warp.sign:
    description: Can warp using signs.
    default: true
  itemstowarp.warp.sign.create:
    description: Can create warp signs.
    default: true
  itemstowarp.warp.sign.remove:
    description: Can remove warp signs.
    default: op
  itemstowarp.list:
    description: Can list non-private warps.
    default: true
  itemstowarp.list.own:
    description: Can list own warps.
    default: true
  itemstowarp.list.all:
    description: Can list all warps, should also have itemstowarp.warp.any
    default: op
  itemstowarp.user:
    description: Includes all basic permissions.
    children:
      itemstowarp.create: true
      itemstowarp.makeprivate: true
      itemstowarp.remove: true
      itemstowarp.warp: true
      itemstowarp.warp.sign: true
      itemstowarp.warp.sign.create: true
      itemstowarp.list: true
      itemstowarp.list.own: true
  itemstowarp.admin:
    description: Includes all admin permissions.
    children:
      itemstowarp.create: true
      itemstowarp.makeprivate.any: true
      itemstowarp.remove.any: true
      itemstowarp.warp.any: true
      itemstowarp.warp.sign: true
      itemstowarp.warp.sign.create: true
      itemstowarp.warp.sign.removeany: true
      itemstowarp.list.all: true
      itemstowarp.list.own: true